### ISSUE TITLE
Django 1.5 issue - new auth model - minor adjustment needed

### ISSUE THREAD

**Issue by jensenbox** [ailabs/django-auth-remember#6]
```
Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x1ddb510>>
Traceback (most recent call last):
  File "/opt/rh/venv/src/django/django/core/management/commands/runserver.py", line 92, in inner_run
    self.validate(display_num_errors=True)
  File "/opt/rh/venv/src/django/django/core/management/base.py", line 281, in validate
    raise CommandError("One or more models did not validate:\n%s" % error_text)
django.core.management.base.CommandError: One or more models did not validate:
auth_remember.remembertoken: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
```

**Comment by jensenbox** [comment]
I copied in the auth_remember folder in and change models.py:

Line 5 is now: 

``` python
from django.conf import settings
```

and line 36 is now: 

``` python
user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="remember_me_tokens")
```

**Comment by jensenbox** [comment]
Separate issue: default date and time for the created column should use the django supplied now() function

Add the following:

``` python
from django.utils.timezone import now
```

and change the created column definition:

``` python
created = models.DateTimeField(editable=False, blank=True,  default=now())
```
